name: Create Rust Release

on:
  push:
    branches:
    - main
    paths:
    - 'Cargo.toml'

permissions: # these permissions are required for the actions to run
  contents: write

jobs:
  auto-release: 
    uses: init4tech/actions/.github/workflows/auto-release-rust.yml@main
    with:
      binary-name: 'zenith-builder-example'
