name: Rust CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust-base:
    uses: init4tech/actions/.github/workflows/rust-base.yml@main
    with: 
      requires-private-deps: true
      install-foundry: true
    secrets: 
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}